/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./**/*.liquid', './assets/**/*.js'],
  safelist: [
    'aspect-square',
    'aspect-[4/5]',
    'aspect-[5/4]',
    'aspect-auto',
    'opacity-50',
    'opacity-100',
    'pointer-events-none',
    'rotate-180',
    "hidden",
    "fixed",
    "inset-0",
    "inset-y-0",
    "inset-x-0",
    "transform",
    "transition-all",
    "z-40",
    "z-50",
    "translate-x-full",
    "-translate-x-full",
    "translate-y-full",
    "-translate-y-full",
    "translate-x-0",
    "translate-y-0",
    "opacity-0",
    "opacity-100",
    "left-0",
    "right-0",
    "top-0",
    "bottom-0",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
